service:
  name: fics
  standard-settings-controller.enabled: true
  simple-worker:
    enabled: true
    name: simple-worker
    wait-on-stop-ms: 1000
    wait-on-restart-ms: 20000
    min-time-per-iteration-ms: 1000
    timeout-runner-life-ms: 60000
    print-statistics-every-ms: 1000
  redis:
    outcome-collections:
      standard-uploader.enabled: true
  channels-api:
    fics-snapshots:
      currencies-v1.enabled: true
      securities-v1.enabled: true
      derivatives-v1.enabled: true

# Логирование
logging:
  level:
    org.springframework: info
    org.springframework.orm: info
    org.springframework.web: info

# Настройки Сервера
server:
  port: 7002

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: validate # create, create-drop, update, validate
      naming.physical-strategy: ru.gx.core.jpa.naming.PhysicalNamingStrategyQuotedImpl
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USER}
    password: ${DATASOURCE_PASS}
    hikari:
      maximum-pool-size: 2
  redis:
    host: ${REDIS_SERVER}
    port: ${REDIS_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true