-- -----------------------------------------------------------------------------
-- Table: Fics.Instruments
-- -----------------------------------------------------------------------------
-- DROP TABLE "Fics"."Instruments";

CREATE TABLE IF NOT EXISTS "Fics"."Instruments"
(
    "Id"                    int                                             NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Type_Id"               smallint                                        NOT NULL,
    "InternalShortName"     varchar(150)    COLLATE pg_catalog."default"    NOT NULL,
    "InternalFullName"      varchar(500)    COLLATE pg_catalog."default"        NULL,
    CONSTRAINT "Instruments_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Instruments_fkey_Type" FOREIGN KEY ("Type_Id") REFERENCES "Fics"."Instruments_Types" ("Id")
) TABLESPACE pg_default;

ALTER TABLE "Fics"."Instruments" OWNER to gxfin;

-- -----------------------------------------------------------------------------
-- Table: Base.Instruments:Codes
-- -----------------------------------------------------------------------------
-- DROP TABLE "Fics"."Instruments:Codes";

CREATE TABLE IF NOT EXISTS "Fics"."Instruments:Codes"
(
    "Instrument_Id"         int                                             NOT NULL,
    "Provider_Id"           smallint                                        NOT NULL,
    "Index"                 smallint                                        NOT NULL,
    "Code"                  varchar(50)     COLLATE pg_catalog."default"    NOT NULL,
    "Name"                  varchar(250)    COLLATE pg_catalog."default"        NULL,
    "DateFrom"              date                                            NOT NULL,
    "DateTo"                date                                                NULL,
    CONSTRAINT "Instruments:Codes_pkey" PRIMARY KEY ("Instrument_Id", "Provider_Id", "Index"),
    CONSTRAINT "Instruments:Codes_fkey_Instrument" FOREIGN KEY ("Instrument_Id") REFERENCES "Fics"."Instruments" ("Id"),
    CONSTRAINT "Instruments:Codes_fkey_Provider" FOREIGN KEY ("Provider_Id") REFERENCES "Fics"."Providers" ("Id")
) TABLESPACE pg_default;

ALTER TABLE "Fics"."Instruments:Codes" OWNER to gxfin;


-- -----------------------------------------------------------------------------
-- Table: Base.Instruments:Guids
-- -----------------------------------------------------------------------------
-- DROP TABLE "Fics"."Instruments:Guids";

CREATE TABLE IF NOT EXISTS "Fics"."Instruments:Guids"
(
    "Instrument_Id"         int                                             NOT NULL,
    "Index"                 smallint                                        NOT NULL,
    "Guid"                  uuid                                            NOT NULL,
    CONSTRAINT "Instruments:Guids_pkey" PRIMARY KEY ("Instrument_Id", "Index"),
    CONSTRAINT "Instruments:Guids_fkey_Instrument" FOREIGN KEY ("Instrument_Id") REFERENCES "Fics"."Instruments" ("Id")
) TABLESPACE pg_default;

ALTER TABLE "Fics"."Instruments:Guids" OWNER to gxfin;

-- -----------------------------------------------------------------------------
-- Table: Base.Instruments=Currencies
-- -----------------------------------------------------------------------------
-- DROP TABLE "Fics"."Instruments=Currencies";

CREATE TABLE IF NOT EXISTS "Fics"."Instruments=Currencies"
(
    "Id"                    int                                             NOT NULL,
    "CodeAlpha2"            char(2)         COLLATE pg_catalog."default"        NULL,
    "CodeAlpha3"            char(3)         COLLATE pg_catalog."default"    NOT NULL,
    "CodeDec"               smallint                                        NOT NULL,
    "Sign"                  varchar(10)     COLLATE pg_catalog."default"    NOT NULL,
    "PartsName"             varchar(100)    COLLATE pg_catalog."default"    NOT NULL,
    "PartsInOne"            int                                             NOT NULL,
    CONSTRAINT "Instruments=Currencies_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Instruments=Currencies_fkey_Id" FOREIGN KEY ("Id") REFERENCES "Fics"."Instruments" ("Id")
) TABLESPACE pg_default;

ALTER TABLE "Fics"."Instruments=Currencies" OWNER to gxfin;

-- -----------------------------------------------------------------------------
-- Table: Base.Instruments=Securities
-- -----------------------------------------------------------------------------
-- DROP TABLE "Fics"."Instruments=Securities";

CREATE TABLE IF NOT EXISTS "Fics"."Instruments=Securities"
(
    "Id"                    int                                             NOT NULL,
    "CodeISIN"              varchar(20)     COLLATE pg_catalog."default"        NULL,
    CONSTRAINT "Instruments=Securities_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Instruments=Securities_fkey_Id" FOREIGN KEY ("Id") REFERENCES "Fics"."Instruments" ("Id")
) TABLESPACE pg_default;

ALTER TABLE "Fics"."Instruments=Securities" OWNER to gxfin;

-- -----------------------------------------------------------------------------
-- Table: Base.Instruments=Derivatives
-- -----------------------------------------------------------------------------
-- DROP TABLE "Fics"."Instruments=Derivatives";

CREATE TABLE IF NOT EXISTS "Fics"."Instruments=Derivatives"
(
    "Id"                    int                                             NOT NULL,
    "BaseInstrument_Id"     int                                                 NULL,
    "ExpireDate"            date                                                NULL,
    CONSTRAINT "Instruments=Derivatives_pkey" PRIMARY KEY ("Id"),
    CONSTRAINT "Instruments=Derivatives_fkey_Id" FOREIGN KEY ("Id") REFERENCES "Fics"."Instruments" ("Id"),
    CONSTRAINT "Instruments=Derivatives_fkey_BaseInstrument_Id" FOREIGN KEY ("BaseInstrument_Id") REFERENCES "Fics"."Instruments" ("Id")
) TABLESPACE pg_default;

ALTER TABLE "Fics"."Instruments=Derivatives" OWNER to gxfin;

INSERT INTO "Fics"."Instruments" ("Id", "Type_Id", "InternalShortName", "InternalFullName")
VALUES
    (1,     1,  'Рубль',        'Российский рубль'),
    (2,     1,  'Доллар США',   'Доллар США'),
    (3,     1,  'Евро',         'Евро')
ON CONFLICT ("Id") DO UPDATE SET
    "Type_Id" = EXCLUDED."Type_Id",
    "InternalShortName" = EXCLUDED."InternalShortName",
    "InternalFullName" = EXCLUDED."InternalFullName";

INSERT INTO "Fics"."Instruments=Currencies" ("Id", "CodeAlpha2", "CodeAlpha3", "CodeDec", "Sign", "PartsName", "PartsInOne")
VALUES
    (1,     'RU',   'RUB',  643,    '₽',    'Копейка',  100),
    (2,     'US',   'USD',  840,    '$',    'Цент',     100),
    (3,     'EU',   'EUR',  978,    '€',    'Евроцент', 100);
